NEFW.KS.L001/NEFW.KS.L001.WebApp/Controllers/OrderItemController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NEFW.KS.L001.Common;
using NEFW.KS.L001.Doman.Dto;
using NEFW.KS.L001.WebApp.Models;
using Newtonsoft.Json;
using System.Text;

namespace NEFW.KS.L001.WebApp.Controllers
{
    public class OrderItemController : Controller
    {
        public async Task<IActionResult> Index()
        {
            var tableResponse = await SendAsync<OrderItemDto>(new APIRequest
            {
                ApiType = SD.ApiType.GET,
                Url = "https://localhost:7206/api/OrderItem"
            });

            List<OrderItemDto> orderItemDtos = new List<OrderItemDto>();
            if (tableResponse.Success)
            {
                orderItemDtos = JsonConvert.DeserializeObject<List<OrderItemDto>>(Convert.ToString(tableResponse.Data));
            }

            return View(orderItemDtos);
        }

        public async Task<IActionResult> Create()
        {
            var listProduct = await SendAsync<ProductDto>(new APIRequest
            {
                ApiType = SD.ApiType.GET,
                Url = "https://localhost:7206/api/Product"
            });
            List<ProductDto> products = JsonConvert.DeserializeObject<List<ProductDto>>(Convert.ToString(listProduct.Data));
            ViewData["ProductId"] = products.Select(x => new SelectListItem
            {
                Value = x.Id.ToString(),
                Text = x.Name
            });

            var listOrder = await SendAsync<OrderDto>(new APIRequest
            {
                ApiType = SD.ApiType.GET,
                Url = "https://localhost:7206/api/Order"
            });
            List<OrderDto> orders = JsonConvert.DeserializeObject<List<OrderDto>>(Convert.ToString(listOrder.Data));
            ViewData["OrderId"] = orders.Select(x => new SelectListItem
            {
                Value = x.Id.ToString(),
                Text = x.Id.ToString()
            });

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([FromBody] OrderItemCreateDto orderItemDto)
        {
            if (!ModelState.IsValid)
            {
                return View(orderItemDto);
            }

            var tableResponse = await SendAsync<OrderItemDto>(new APIRequest
            {
                ApiType = SD.ApiType.POST,
                Url = "https://localhost:7206/api/OrderItem",
                Data = orderItemDto
            });

            if (tableResponse.Success)
            {
                return RedirectToAction(nameof(Index));
            }

            var listOrder = await SendAsync<OrderDto>(new APIRequest
            {
                ApiType = SD.ApiType.GET,
                Url = "https://localhost:7206/api/Order"
            });
            List<OrderDto> orders = JsonConvert.DeserializeObject<List<OrderDto>>(Convert.ToString(listOrder.Data));
            ViewData["OrderId"] = orders.Select(x => new SelectListItem
            {
                Value = x.Id.ToString(),
                Text = x.Id.ToString()
            });

            var listProduct = await SendAsync<ProductDto>(new APIRequest
            {
                ApiType = SD.ApiType.GET,
                Url = "https://localhost:7206/api/Product"
            });
            List<ProductDto> products = JsonConvert.DeserializeObject<List<ProductDto>>(Convert.ToString(listProduct.Data));
            ViewData["ProductId"] = products.Select(x => new SelectListItem
            {
                Value = x.Id.ToString(),
                Text = x.Name
            });
            return View(orderItemDto);
        }

        public async Task<IActionResult> Update(int id)
        {
            var tableResponse = await SendAsync<OrderItemDto>(new APIRequest
            {
                ApiType = SD.ApiType.GET,
                Url = $"https://localhost:7206/api/OrderItem/{id}"
            });

            OrderItemUpdateDto orderItemDto = new OrderItemUpdateDto();
            if (tableResponse.Success)
            {
                orderItemDto = JsonConvert.DeserializeObject<OrderItemUpdateDto>(Convert.ToString(tableResponse.Data));
            }

            var listOrder = await SendAsync<OrderDto>(new APIRequest
            {
                ApiType = SD.ApiType.GET,
                Url = "https://localhost:7206/api/Order"
            });
            List<OrderDto> orders = JsonConvert.DeserializeObject<List<OrderDto>>(Convert.ToString(listOrder.Data));
            ViewData["OrderId"] = orders.Select(x => new SelectListItem
            {
                Value = x.Id.ToString(),
                Text = x.Id.ToString()
            });

            var listProduct = await SendAsync<ProductDto>(new APIRequest
            {
                ApiType = SD.ApiType.GET,
                Url = "https://localhost:7206/api/Product"
            });
            List<ProductDto> products = JsonConvert.DeserializeObject<List<ProductDto>>(Convert.ToString(listProduct.Data));
            ViewData["ProductId"] = products.Select(x => new SelectListItem
            {
                Value = x.Id.ToString(),
                Text = x.Name
            });
            return View(orderItemDto);
        }

        [HttpPost]
        public async Task<IActionResult> Update([FromBody] OrderItemUpdateDto orderItemDto)
        {
            if (!ModelState.IsValid)
            {
                return View(orderItemDto);
            }

            var tableResponse = await SendAsync<OrderItemDto>(new APIRequest
            {
                ApiType = SD.ApiType.PUT,
                Url = $"https://localhost:7206/api/OrderItem/{orderItemDto.Id}",
                Data = orderItemDto
            });

            if (tableResponse.Success)
            {
                return RedirectToAction(nameof(Index));
            }

            var listOrder = await SendAsync<OrderDto>(new APIRequest
            {
                ApiType = SD.ApiType.GET,
                Url = "https://localhost:7206/api/Order"
            });
            List<OrderDto> orders = JsonConvert.DeserializeObject<List<OrderDto>>(Convert.ToString(listOrder.Data));
            ViewData["OrderId"] = orders.Select(x => new SelectListItem
            {
                Value = x.Id.ToString(),
                Text = x.Id.ToString()
            });

            var listProduct = await SendAsync<ProductDto>(new APIRequest
            {
                ApiType = SD.ApiType.GET,
                Url = "https://localhost:7206/api/Product"
            });
            List<ProductDto> products = JsonConvert.DeserializeObject<List<ProductDto>>(Convert.ToString(listProduct.Data));
            ViewData["ProductId"] = products.Select(x => new SelectListItem
            {
                Value = x.Id.ToString(),
                Text = x.Name
            });
            return View(orderItemDto);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var tableResponse = await SendAsync<OrderItemDto>(new APIRequest
            {
                ApiType = SD.ApiType.GET,
                Url = $"https://localhost:7206/api/OrderItem/{id}"
            });

            OrderItemDto orderItemDto = new OrderItemDto();
            if (tableResponse.Success)
            {
                orderItemDto = JsonConvert.DeserializeObject<OrderItemDto>(Convert.ToString(tableResponse.Data));
            }

            return View(orderItemDto);
        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromBody] OrderItemDto orderItemDto)
        {
            var tableResponse = await SendAsync<OrderItemDto>(new APIRequest
            {
                ApiType = SD.ApiType.DELETE,
                Url = $"https://localhost:7206/api/OrderItem/{orderItemDto.Id}"
            });

            if (tableResponse.Success)
            {
                return RedirectToAction(nameof(Index));
            }

            return View(orderItemDto);
        }

        public async Task<TableResponse<T>> SendAsync<T>(APIRequest apiRequest)
        {
            try
            {
                var client = new HttpClient();
                HttpRequestMessage message = new HttpRequestMessage();
                message.Headers.Add("Accept", "application/json");
                message.RequestUri = new Uri(apiRequest.Url);
                if (apiRequest.Data != null)
                {
                    message.Content = new StringContent(JsonConvert.SerializeObject(apiRequest.Data),
                        Encoding.UTF8, "application/json");
                }
                switch (apiRequest.ApiType)
                {
                    case SD.ApiType.POST:
                        message.Method = HttpMethod.Post;
                        break;
                    case SD.ApiType.PUT:
                        message.Method = HttpMethod.Put;
                        break;
                    case SD.ApiType.DELETE:
                        message.Method = HttpMethod.Delete;
                        break;
                    default:
                        message.Method = HttpMethod.Get;
                        break;

                }

                HttpResponseMessage apiResponse = null;

                apiResponse = await client.SendAsync(message);

                TableResponse<T> tableResponse = new TableResponse<T>();

                if (apiResponse.IsSuccessStatusCode)
                {
                    string jsonResponse = await apiResponse.Content.ReadAsStringAsync();
                    tableResponse = JsonConvert.DeserializeObject<TableResponse<T>>(jsonResponse);
                }
                else
                {
                    tableResponse.Code = (int)apiResponse.StatusCode;
                    tableResponse.Success = false;
                    tableResponse.Message = "failed";
                }

                return tableResponse;

            }

NEFW.KS.L001/NEFW.KS.L001.WebApp/Views/OrderItem/Create.cshtml
@model OrderItemCreateDto

<form asp-action="Create">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Create OrderItem</h1>
        <hr />

        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="OrderId" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="OrderId" class="form-control" asp-items="ViewBag.OrderId" id="orderId" required></select>
                <span asp-validation-for="OrderId" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="ProductId" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="ProductId" class="form-control" asp-items="ViewBag.ProductId" id="productId" required></select>
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Quantity" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Quantity" class="form-control" id="quantity" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>

            <div class="col-5">
                <input type="button" id="submit" value="Create" class="btn btn-success form-control" />
            </div>
        </div>
    </div>
</form>

<script>
    $(document).ready(function () {
        $("#submit").click(function () {
            var orderIdData = $("#orderId").val();
            var productIdData = $("#productId").val();
            var quantityData = $("#quantity").val();
            $.ajax({
                url: '/OrderItem/Create',
                type: 'POST',
                contentType: 'application/json',
                data: JSON.stringify({ OrderId: orderIdData, ProductId: productIdData, Quantity: quantityData }),
                success: function (response) {
                    window.location.href = '/OrderItem'
                },
                error: function (error) {
                }
            });

        });
    });

</script>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

NEFW.KS.L001/NEFW.KS.L001.WebApp/Views/OrderItem/Delete.cshtml
@model OrderItemDto

<form asp-action="Delete">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Delete OrderItem</h1>
        <hr />

        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="Id" id="id" type="hidden" />

            <div class="col-2">
                <label asp-for="Id" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Id" class="form-control" id="Id" disabled />
            </div>

            <div class="col-2">
                <label asp-for="Order.Id" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Order.Id" class="form-control" id="Id" disabled />
            </div>

            <div class="col-2">
                <label asp-for="Product.Name" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Product.Name" class="form-control" id="Id" disabled />
            </div>

            <div class="col-2">
                <label asp-for="Quantity" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Quantity" class="form-control" id="Id" disabled />
            </div>

            <div class="col-5">
                <input type="button" id="submit" value="Delete" class="btn btn-success form-control" />
            </div>
        </div>
    </div>
</form>

<script>
    $(document).ready(function () {
        $("#submit").click(function () {
            var idData = $("#id").val();
            $.ajax({
                url: '/OrderItem/Delete',
                type: 'POST',
                contentType: 'application/json',
                data: JSON.stringify({ id: idData }),
                success: function (response) {
                    window.location.href = '/OrderItem'
                },
                error: function (error) {

                }
            });

        });
    });

</script>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

NEFW.KS.L001/NEFW.KS.L001.WebApp/Views/OrderItem/Index.cshtml
@using Newtonsoft.Json
@model IEnumerable<OrderItemDto>

<div class="container">
    <h1 class="h3 mb-2 text-gray-800">OrderItem List</h1>
    <div class="h3 mb-2 row">
        <div class="col-md-12 col-lg-2">
            <a href="@Url.Action("Create", "OrderItem")" class="btn btn-success btn-icon-split">
                <span class="icon text-white-50">
                    <i class="fas fa-plus"></i>
                </span>
                <span class="text">Add</span>
            </a>
        </div>
    </div>

    <div class="card shadow mb-4">
        <div class="card-body">
            <table class="table table-bordered" id="entityTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>OrderId</th>
                        <th>Product Name</th>
                        <th>Quantity</th>
                        <th></th>
                        <!-- Thêm các cột khác tùy theo dữ liệu cần hiển thị -->
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.Order.Id</td>
                            <td>@item.Product.Name</td>
                            <td>@item.Quantity</td>
                            <td>
                                <a asp-controller="OrderItem" asp-action="Update" asp-route-id="@item.Id" class="btn btn-success">Update</a>
                                <a asp-controller="OrderItem" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Detele</a>
                            </td>
                            <!-- Hiển thị các cột khác tương ứng -->
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

NEFW.KS.L001/NEFW.KS.L001.WebApp/Views/OrderItem/Update.cshtml
@model OrderItemUpdateDto

<form asp-action="Update">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Update OrderItem</h1>
        <hr />

        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="Id" id="id" type="hidden" />

            <div class="col-2">
                <label asp-for="OrderId" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="OrderId" class="form-control" asp-items="ViewBag.OrderId" id="orderId" required></select>
                <span asp-validation-for="OrderId" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="ProductId" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="ProductId" class="form-control" asp-items="ViewBag.ProductId" id="productId" required></select>
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Quantity" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Quantity" class="form-control" id="quantity" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>

            <div class="col-5">
                <input type="button" id="submit" value="Update" class="btn btn-success form-control" />
            </div>
        </div>
    </div>
</form>

<script>
    $(document).ready(function () {
        $("#submit").click(function () {
            var idData = $("#id").val();
            var orderIdData = $("#orderId").val();
            var productIdData = $("#productId").val();
            var quantityData = $("#quantity").val();
            $.ajax({
                url: '/OrderItem/Update',
                type: 'POST',
                contentType: 'application/json',
                data: JSON.stringify({ id: idData, OrderId: orderIdData, ProductId: productIdData, Quantity: quantityData }),
                success: function (response) {
                    window.location.href = '/OrderItem'
                },
                error: function (error) {
                }
            });

        });
    });

</script>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}