NEFW.KS.L001/NEFW.KS.L001.WebApp/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using NEFW.KS.L001.Common;
using NEFW.KS.L001.Doman.Dto;
using NEFW.KS.L001.WebApp.Models;
using Newtonsoft.Json;
using System.Text;

namespace NEFW.KS.L001.WebApp.Controllers
{
    public class ProductController : Controller
    {
        public async Task<IActionResult> Index()
        {
            var tableResponse = await SendAsync(new APIRequest
            {
                ApiType = SD.ApiType.GET,
                Url = "https://localhost:7206/api/Product"
            });

            List<ProductDto> productDtos = new List<ProductDto>();
            if (tableResponse.Success)
            {
                productDtos = JsonConvert.DeserializeObject<List<ProductDto>>(Convert.ToString(tableResponse.Data));
            }

            return View(productDtos);
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([FromBody] ProductCreateDto productDto)
        {
            if (!ModelState.IsValid)
            {
                return View(productDto);
            }

            var tableResponse = await SendAsync(new APIRequest
            {
                ApiType = SD.ApiType.POST,
                Url = "https://localhost:7206/api/Product",
                Data = productDto
            });

            if (tableResponse.Success)
            {
                return RedirectToAction(nameof(Index));
            }

            return View(productDto);
        }

        public async Task<IActionResult> Update(int id)
        {
            var tableResponse = await SendAsync(new APIRequest
            {
                ApiType = SD.ApiType.GET,
                Url = $"https://localhost:7206/api/Product/{id}"
            });

            ProductDto productDto = new ProductDto();
            if (tableResponse.Success)
            {
                productDto = JsonConvert.DeserializeObject<ProductDto>(Convert.ToString(tableResponse.Data));
            }

            return View(productDto);
        }

        [HttpPost]
        public async Task<IActionResult> Update([FromBody] ProductDto productDto)
        {
            if (!ModelState.IsValid)
            {
                return View(productDto);
            }

            var tableResponse = await SendAsync(new APIRequest
            {
                ApiType = SD.ApiType.PUT,
                Url = $"https://localhost:7206/api/Product/{productDto.Id}",
                Data = productDto
            });

            if (tableResponse.Success)
            {
                return RedirectToAction(nameof(Index));
            }

            return View(productDto);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var tableResponse = await SendAsync(new APIRequest
            {
                ApiType = SD.ApiType.GET,
                Url = $"https://localhost:7206/api/Product/{id}"
            });

            ProductDto productDto = new ProductDto();
            if (tableResponse.Success)
            {
                productDto = JsonConvert.DeserializeObject<ProductDto>(Convert.ToString(tableResponse.Data));
            }

            return View(productDto);
        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromBody] ProductDto productDto)
        {
            var tableResponse = await SendAsync(new APIRequest
            {
                ApiType = SD.ApiType.DELETE,
                Url = $"https://localhost:7206/api/Product/{productDto.Id}"
            });

            if (tableResponse.Success)
            {
                return RedirectToAction(nameof(Index));
            }

            return View(productDto);
        }

        public async Task<TableResponse<ProductDto>> SendAsync(APIRequest apiRequest)
        {
            try
            {
                var client = new HttpClient();
                HttpRequestMessage message = new HttpRequestMessage();
                message.Headers.Add("Accept", "application/json");
                message.RequestUri = new Uri(apiRequest.Url);
                if (apiRequest.Data != null)
                {
                    message.Content = new StringContent(JsonConvert.SerializeObject(apiRequest.Data),
                        Encoding.UTF8, "application/json");
                }
                switch (apiRequest.ApiType)
                {
                    case SD.ApiType.POST:
                        message.Method = HttpMethod.Post;
                        break;
                    case SD.ApiType.PUT:
                        message.Method = HttpMethod.Put;
                        break;
                    case SD.ApiType.DELETE:
                        message.Method = HttpMethod.Delete;
                        break;
                    default:
                        message.Method = HttpMethod.Get;
                        break;

                }

                HttpResponseMessage apiResponse = null;

                apiResponse = await client.SendAsync(message);

                TableResponse<ProductDto> tableResponse = new TableResponse<ProductDto>();

                if (apiResponse.IsSuccessStatusCode)
                {
                    string jsonResponse = await apiResponse.Content.ReadAsStringAsync();
                    tableResponse = JsonConvert.DeserializeObject<TableResponse<ProductDto>>(jsonResponse);
                }
                else
                {
                    tableResponse.Code = (int)apiResponse.StatusCode;
                    tableResponse.Success = false;
                    tableResponse.Message = "failed";
                }

                return tableResponse;

            }
            catch (Exception e)
            {
                var dto = new TableResponse<ProductDto>
                {
                    Message = e.Message,
                    Success = false
                };
                var res = JsonConvert.SerializeObject(dto);
                var APIResponse = JsonConvert.DeserializeObject<TableResponse<ProductDto>>(res);
                return APIResponse;
            }
        }
    }

}

NEFW.KS.L001/NEFW.KS.L001.WebApp/Views/Product/Create.cshtml
@model ProductCreateDto

<form asp-action="Create">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Create Product</h1>
        <hr />

        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="Name" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Name" class="form-control" id="name" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Description" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Description" class="form-control" id="description" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Price" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Price" class="form-control" type="number" step="0.1" id="price" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>


            <div class="col-5">
                <input type="button" id="submit" value="Create" class="btn btn-success form-control" />
            </div>
        </div>
    </div>
</form>

<script>
    $(document).ready(function () {
        $("#submit").click(function () {
            var nameData = $("#name").val();
            var descriptionData = $("#description").val();
            var priceData = $("#price").val();
            $.ajax({
                url: '/Product/Create',
                type: 'POST',
                contentType: 'application/json',
                data: JSON.stringify({ name: nameData, description: descriptionData, price: priceData }),
                success: function (response) {
                    window.location.href = '/Product'
                },
                error: function (error) {
                    alert('Error adding product');
                }
            });

        });
    });

</script>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

NEFW.KS.L001/NEFW.KS.L001.WebApp/Views/Product/Delete.cshtml
@model ProductDto

<form>
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Create Product</h1>
        <hr />

        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="Id" id="id" type="hidden" />

            <div class="col-2">
                <label asp-for="Name" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Name" class="form-control" id="name" disabled />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Description" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Description" class="form-control" id="description" disabled />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Price" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Price" class="form-control" type="text" step="0.1" id="price" disabled />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>


            <div class="col-5">
                <input type="button" id="submit" value="Delete" class="btn btn-success form-control" />
            </div>
        </div>
    </div>
</form>

<script>
    $(document).ready(function () {
        $("#submit").click(function () {
            var idData = $("#id").val();
            var nameData = $("#name").val();
            var descriptionData = $("#description").val();
            var priceData = $("#price").val();
            $.ajax({
                url: '/Product/Delete',
                type: 'POST',
                contentType: 'application/json',
                data: JSON.stringify({ id: idData, name: nameData, description: descriptionData, price: priceData }),
                success: function (response) {
                    window.location.href = '/Product'
                },
                error: function (error) {
                    alert('Error adding product');
                }
            });

        });
    });

</script>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

NEFW.KS.L001/NEFW.KS.L001.WebApp/Views/Product/Index.cshtml
@using Newtonsoft.Json
@model IEnumerable<ProductDto>

<div class="container">
    <h1 class="h3 mb-2 text-gray-800">Customer List</h1>
    <div class="h3 mb-2 row">
        <div class="col-md-12 col-lg-2">
            <a href="@Url.Action("Create", "Product")" class="btn btn-success btn-icon-split">
                <span class="icon text-white-50">
                    <i class="fas fa-plus"></i>
                </span>
                <span class="text">Add</span>
            </a>
        </div>
    </div>

    <div class="card shadow mb-4">
        <div class="card-body">
            <table class="table table-bordered" id="entityTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Desciption</th>
                        <th>Price</th>
                        <th></th>
                        <!-- Thêm các cột khác tùy theo dữ liệu cần hiển thị -->
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.Name</td>
                            <td>@item.Description</td>
                            <td>@item.Price</td>
                            <td>
                                <a asp-controller="Product" asp-action="Update" asp-route-id="@item.Id" class="btn btn-success">Update</a>
                                <a asp-controller="Product" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Detele</a>
                            </td>
                            <!-- Hiển thị các cột khác tương ứng -->
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

NEFW.KS.L001/NEFW.KS.L001.WebApp/Views/Product/Update.cshtml
@model ProductDto

<form asp-action="Update">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Create Product</h1>
        <hr />

        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="Id" id="id" type="hidden" />

            <div class="col-2">
                <label asp-for="Name" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Name" class="form-control" id="name" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Description" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Description" class="form-control" id="description" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Price" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Price" class="form-control" type="text" step="0.1" id="price" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>


            <div class="col-5">
                <input type="button" id="submit" value="Update" class="btn btn-success form-control" />
            </div>
        </div>
    </div>
</form>

<script>
    $(document).ready(function () {
        $("#submit").click(function () {
            var idData = $("#id").val();
            var nameData = $("#name").val();
            var descriptionData = $("#description").val();
            var priceData = $("#price").val();
            $.ajax({
                url: '/Product/Update',
                type: 'POST',
                contentType: 'application/json',
                data: JSON.stringify({id: idData, name: nameData, description: descriptionData, price: priceData }),
                success: function (response) {
                    window.location.href = '/Product'
                },
                error: function (error) {
                    alert('Error adding product');
                }
            });

        });
    });

</script>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}