NEFW.KS.L001/NEFW.KS.L001.WebApp/Controllers/CustomerController.cs
using Azure;
using Microsoft.AspNetCore.Mvc;
using NEFW.KS.L001.Common;
using NEFW.KS.L001.Doman.Dto;
using NEFW.KS.L001.Infastructor.Entity;
using NEFW.KS.L001.WebApp.Models;
using Newtonsoft.Json;
using System.Net.Http;
using System.Text;

namespace NEFW.KS.L001.WebApp.Controllers
{
    public class CustomerController : Controller
    {
        public async Task<IActionResult> Index()
        {
            var tableResponse = await SendAsync(new APIRequest
            {
                ApiType = SD.ApiType.GET,
                Url = "https://localhost:7206/api/Customer"
            });

            List<CustomerDto> customerDtos = new List<CustomerDto>();
            if (tableResponse.Success)
            {
                customerDtos = JsonConvert.DeserializeObject<List<CustomerDto>>(Convert.ToString(tableResponse.Data));
            }
           
            return View(customerDtos);
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([FromBody] CustomerCreateDto customerDto)
        {
            if (!ModelState.IsValid)
            {
                return View(customerDto);
            }

            var tableResponse = await SendAsync(new APIRequest
            {
                ApiType = SD.ApiType.POST,
                Url = "https://localhost:7206/api/Customer",
                Data = customerDto
            });

            if (tableResponse.Success)
            {
                return RedirectToAction(nameof(Index));
            }

            return View(customerDto);
        }

        public async Task<IActionResult> Update(int id)
        {
            var tableResponse = await SendAsync(new APIRequest
            {
                ApiType = SD.ApiType.GET,
                Url = $"https://localhost:7206/api/Customer/{id}"
            });

            CustomerDto customerDto = new CustomerDto();
            if (tableResponse.Success)
            {
                customerDto = JsonConvert.DeserializeObject<CustomerDto>(Convert.ToString(tableResponse.Data));
            }

            return View(customerDto);
        }

        [HttpPost]
        public async Task<IActionResult> Update([FromBody] CustomerDto customerDto)
        {
            if (!ModelState.IsValid)
            {
                return View(customerDto);
            }

            var tableResponse = await SendAsync(new APIRequest
            {
                ApiType = SD.ApiType.PUT,
                Url = $"https://localhost:7206/api/Customer/{customerDto.Id}",
                Data = customerDto
            });

            if (tableResponse.Success)
            {
                return RedirectToAction(nameof(Index));
            }

            return View(customerDto);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var tableResponse = await SendAsync(new APIRequest
            {
                ApiType = SD.ApiType.GET,
                Url = $"https://localhost:7206/api/Customer/{id}"
            });

            CustomerDto customerDto = new CustomerDto();
            if (tableResponse.Success)
            {
                customerDto = JsonConvert.DeserializeObject<CustomerDto>(Convert.ToString(tableResponse.Data));
            }

            return View(customerDto);
        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromBody] CustomerDto customerDto)
        {
            var tableResponse = await SendAsync(new APIRequest
            {
                ApiType = SD.ApiType.DELETE,
                Url = $"https://localhost:7206/api/Customer/{customerDto.Id}"
            });

            if (tableResponse.Success)
            {
                return RedirectToAction(nameof(Index));
            }

            return View(customerDto);
        }

        public async Task<TableResponse<CustomerDto>> SendAsync(APIRequest apiRequest)
        {
            try
            {
                var client = new HttpClient();
                HttpRequestMessage message = new HttpRequestMessage();
                message.Headers.Add("Accept", "application/json");
                message.RequestUri = new Uri(apiRequest.Url);
                if (apiRequest.Data != null)
                {
                    message.Content = new StringContent(JsonConvert.SerializeObject(apiRequest.Data),
                        Encoding.UTF8, "application/json");
                }
                switch (apiRequest.ApiType)
                {
                    case SD.ApiType.POST:
                        message.Method = HttpMethod.Post;
                        break;
                    case SD.ApiType.PUT:
                        message.Method = HttpMethod.Put;
                        break;
                    case SD.ApiType.DELETE:
                        message.Method = HttpMethod.Delete;
                        break;
                    default:
                        message.Method = HttpMethod.Get;
                        break;

                }

                HttpResponseMessage apiResponse = null;

                apiResponse = await client.SendAsync(message);

                TableResponse<CustomerDto> tableResponse = new TableResponse<CustomerDto>();

                if (apiResponse.IsSuccessStatusCode)
                {
                    string jsonResponse = await apiResponse.Content.ReadAsStringAsync();
                    tableResponse = JsonConvert.DeserializeObject<TableResponse<CustomerDto>>(jsonResponse);
                }
                else
                {
                    tableResponse.Code = (int)apiResponse.StatusCode;
                    tableResponse.Success = false;
                    tableResponse.Message = "failed";
                }

                return tableResponse;

            }
            catch (Exception e)
            {
                var dto = new TableResponse<CustomerDto>
                {
                    Message = e.Message,
                    Success = false
                };
                var res = JsonConvert.SerializeObject(dto);
                var APIResponse = JsonConvert.DeserializeObject<TableResponse<CustomerDto>>(res);
                return APIResponse;
            }
        }
    }
}

NEFW.KS.L001/NEFW.KS.L001.WebApp/Views/Customer/Create.cshtml
@model CustomerDto

<form asp-action="Create">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Create Customer</h1>
        <hr />

        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="Name" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Name" class="form-control" id="name" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Email" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Email" class="form-control" id="email" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="col-5">
                <input type="button" id="submit" value="Create" class="btn btn-success form-control" />
            </div>
        </div>
    </div>
</form>

<script>
    $(document).ready(function () {
        $("#submit").click(function () {
            var nameData = $("#name").val();
            var emailData = $("#email").val();
            $.ajax({
                url: '/Customer/Create',
                type: 'POST',
                contentType: 'application/json',
                data: JSON.stringify({ name: nameData, email: emailData }),
                success: function (response) {
                    window.location.href = '/Customer'
                },
                error: function (error) {
                    alert('Error adding product');
                }
            });

        });
    });

</script>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

NEFW.KS.L001/NEFW.KS.L001.WebApp/Views/Customer/Delete.cshtml
@model CustomerDto

<form asp-action="Delete">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Delete Customer</h1>
        <hr />

        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="Id" id="id" type="hidden" />

            <div class="col-2">
                <label asp-for="Name" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Name" class="form-control" id="name" disabled />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Email" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Email" class="form-control" id="email" disabled />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="col-5">
                <input type="button" id="submit" value="Delete" class="btn btn-danger form-control" />
            </div>
        </div>
    </div>
</form>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

<script>
    $(document).ready(function () {
        $("#submit").click(function () {
            var idData = $("#id").val();
            var nameData = $("#name").val();
            var emailData = $("#email").val();
            $.ajax({
                url: '/Customer/Delete',
                type: 'POST',
                contentType: 'application/json',
                data: JSON.stringify({id: idData, name: nameData, email: emailData }),
                success: function (response) {
                    window.location.href = '/Customer'
                },
                error: function (error) {
                    alert('Error');
                }
            });

        });
    });

</script>

NEFW.KS.L001/NEFW.KS.L001.WebApp/Views/Customer/Index.cshtml
@using Newtonsoft.Json
@model IEnumerable<CustomerDto>
<div class="container">
    <h1 class="h3 mb-2 text-gray-800">Customer List</h1>
    <div class="h3 mb-2 row">
        <div class="col-md-12 col-lg-2">
            <a href="@Url.Action("Create", "Customer")" class="btn btn-success btn-icon-split">
                <span class="icon text-white-50">
                    <i class="fas fa-plus"></i>
                </span>
                <span class="text">Add</span>
            </a>
        </div>
    </div>

    <div class="card shadow mb-4">
        <div class="card-body">
            <table class="table table-bordered" id="entityTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th></th>
                        <!-- Thêm các cột khác tùy theo dữ liệu cần hiển thị -->
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.Name</td>
                            <td>@item.Email</td>
                            <td>
                                <a asp-controller="Customer" asp-action="Update" asp-route-id="@item.Id" class="btn btn-success">Update</a>
                                <a asp-controller="Customer" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Detele</a>
                            </td>
                            <!-- Hiển thị các cột khác tương ứng -->
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

NEFW.KS.L001/NEFW.KS.L001.WebApp/Views/Customer/Update.cshtml
@model CustomerDto

<form asp-action="Update">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Update Customer</h1>
        <hr />

        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="Id" id="id" type="hidden"/>

            <div class="col-2">
                <label asp-for="Name" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Name" class="form-control" id="name" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Email" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Email" class="form-control" id="email" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="col-5">
                <input type="button" id="submit" value="Update" class="btn btn-success form-control" />
            </div>
        </div>
    </div>
</form>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

<script>
    $(document).ready(function () {
        $("#submit").click(function () {
            var idData = $("#id").val();
            var nameData = $("#name").val();
            var emailData = $("#email").val();
            $.ajax({
                url: `/Customer/Update`,
                type: 'POST',
                contentType: 'application/json',
                data: JSON.stringify({id: idData, name: nameData, email: emailData }),
                success: function (response) {
                    window.location.href = '/Customer'
                },
                error: function (error) {
                    alert('Error');
                }
            });

        });
    });

</script>